# Generated by Django 4.2.2 on 2023-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_organization_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('наблюдатель', 'наблюдатель'), ('базовый пользователь', 'базовый пользователь'), ('ПМ', 'ПМ'), ('создатель', 'создатель'), ('запрещено', 'запрещено')], max_length=20),
        ),
    ]
