# Generated by Django 4.2.2 on 2023-07-04 06:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_alter_organizationuser_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='organizationuser',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='projectuser',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='subtask_id',
            new_name='subtask',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='taskfile',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='taskimage',
            old_name='task_id',
            new_name='task',
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('organization', 'user')},
        ),
    ]
