# Generated by Django 4.2.2 on 2023-09-04 08:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_comment_created_at_alter_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskfile',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_finish',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 4, 8, 27, 49, 294777, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
