# Generated by Django 4.2.2 on 2023-07-17 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_organization_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_finish',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 17, 4, 59, 31, 868726, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 17, 4, 59, 41, 366057, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
