# Generated by Django 4.2.2 on 2023-07-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='is_active',
        ),
    ]
