# Generated by Django 4.2.2 on 2023-08-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_in_chat',
            field=models.BooleanField(default=False, verbose_name='Уведомлять в телеграмм'),
        ),
    ]
